---
title: "HBF_Analysis"
author: "Elizabeth Keeley"
date: "2026-03-18"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(ggplot2)
library(dplyr)
```


```{r}
# bring in datasets for Jul 31 and filter for biomassC by Time

HBF_1yr <- read.csv(here("HBF/HBF.1yr.out"), stringsAsFactors = TRUE) # 1 year steady state run, daily output
HBF_1yr_biomassC <- HBF_1yr %>% select(Time, biomassC) 
HBF_1yr_biomassC <- rename(HBF_1yr_biomassC, Oneyr_biomassC = biomassC)

HBF_Ca_Jul31 <- read.csv(here("HBF/HBF.Ca.Jul31.out"), stringsAsFactors = TRUE) # doubling of CO2
HBF_Ca_Jul31_biomassC <- HBF_Ca_Jul31 %>% select(Time, biomassC)
HBF_Ca_Jul31_biomassC <- rename(HBF_Ca_Jul31_biomassC, Ca_biomassC = biomassC)

HBF_Calld_Jul31 <- read.csv(here("HBF/HBF.Calld.Jul31.out"), stringsAsFactors = TRUE) # combined doubling of CO2, 3.5oC warming, and 20% decrease in precipitation
HBF_Calld_Jul31_biomassC <- HBF_Calld_Jul31 %>% select(Time, biomassC)
HBF_Calld_Jul31_biomassC <- rename(HBF_Calld_Jul31_biomassC, Calld_biomassC = biomassC)

HBF_Calli_Jul31 <- read.csv(here("HBF/HBF.Calli.Jul31.out"), stringsAsFactors = TRUE) # combined doubling of CO2, 3.5oC warming, and 20% increase in precipitation
HBF_Calli_Jul31_biomassC <- HBF_Calli_Jul31 %>% select(Time, biomassC)
HBF_Calli_Jul31_biomassC <- rename(HBF_Calli_Jul31_biomassC, Calli_biomassC = biomassC)

HBF_Pptd_Jul31 <- read.csv(here("HBF/HBF.Pptd.Jul31.out"), stringsAsFactors = TRUE) # 20% decrease in precipitation	
HBF_Pptd_Jul31_biomassC <- HBF_Pptd_Jul31 %>% select(Time, biomassC)
HBF_Pptd_Jul31_biomassC <- rename(HBF_Pptd_Jul31_biomassC, Pptd_biomassC = biomassC)

HBF_Ppti_Jul31 <- read.csv(here("HBF/HBF.Ppti.Jul31.out"), stringsAsFactors = TRUE) # 20% increase in precipitation
HBF_Ppti_Jul31_biomassC <- HBF_Ppti_Jul31 %>% select(Time, biomassC)
HBF_Ppti_Jul31_biomassC <- rename(HBF_Ppti_Jul31_biomassC, Ppti_biomassC = biomassC)

HBF_T_Jul31 <- read.csv(here("HBF/HBF.T.Jul31.out"), stringsAsFactors = TRUE) # 3.5degreesC warming
HBF_T_Jul31_biomassC <- HBF_T_Jul31 %>% select(Time, biomassC)
HBF_T_Jul31_biomassC <- rename(HBF_T_Jul31_biomassC, T_biomassC = biomassC)
```

```{r}
# combine into one data frame
HBF_alltreats <- bind_cols(Time=HBF_Ca_Jul31_biomassC$Time,Ca_biomassC= HBF_Ca_Jul31_biomassC$Ca_biomassC, Calld_biomassC=HBF_Calld_Jul31_biomassC$Calld_biomassC, Calli_biomassC = HBF_Calli_Jul31_biomassC$Calli_biomassC, Pptd_biomassC = HBF_Pptd_Jul31_biomassC$Pptd_biomassC, Ppti_biomassC = HBF_Ppti_Jul31_biomassC$Ppti_biomassC, T_biomassC = HBF_T_Jul31_biomassC$T_biomassC)

# put "time" in terms of years
HBF_alltreats <- HBF_alltreats %>%
  mutate(Time_yrs = Time/365 )

```


```{r}
# attempt at a figure
# ggplot(HBF_alltreats, aes(x=Time, y=)) +
#   geom_line()
HBF_figure<-ggplot(HBF_alltreats, aes(x = Time_yrs)) +
  geom_line(aes(y = Ca_biomassC, color = "Ca")) +
  geom_line(aes(y = Calld_biomassC, color = "Calld")) +
  geom_line(aes(y = Calli_biomassC, color = "Calli")) +
  geom_line(aes(y = Pptd_biomassC, color = "Pptd")) +
  geom_line(aes(y = Ppti_biomassC, color = "Ppti")) +
  geom_line(aes(y = T_biomassC, color = "T")) +
  theme_bw()+
  labs(x="Time (years)",y="Carbon Biomass (g/m2)", title="Change in Carbon Biomass Accumulation over 100 years by Treatment Type", subtitle="Hubbard Brook Experimental Forest", "colour"="Treatment Type", caption="Ca: Doubling of atmospheric CO2.\nCalld: CO2 doubling, 3.5 degrees Celsius warming, and 20% decrease in precipitation.\nCalli: CO2 doubling, 3.5 degrees Celsius warming, and 20% increase in precipitation.\nPptd: 20% decrease in precipitation.\nPPti: 20% increase in precipitation.\nT:3.5 degrees Celsius warming.")+
  theme(plot.caption = element_text( hjust = 0))

HBF_figure
  
```
```{r}
# export figure
ggsave("HBF_expl_fig.png", plot = HBF_figure)
```
 


